/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "database.h"

rpc_args *
action_1_svc(struct rpc_args *argp, struct svc_req *rqstp)
{
	static rpc_args  result;

	/*
	 * insert server code here
	 */

	return &result;
}
