/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "database.h"


void
database_1(char *host)
{
	printf("running client\n");

	CLIENT *clnt;
	rpc_args  *result_1;
	// struct rpc_args  action_1_arg;
	struct rpc_args *args = malloc(sizeof(struct rpc_args));

	result_1 = action_1(&action_1_arg, clnt);
	if (result_1 == (rpc_args *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	if (strcmp(argv[2], "GET") == 0) {

		strcpy(args->action, argv[2]);
		strcpy(args->id, argv[3]);

		printf("Client %d has issued a GET request\n", args->id);

	//PUT message
	} else if (strcmp(argv[2], "PUT") == 0) {
		strcpy(args->action, argv[2]);
		strcpy(args->id, argv[3]);
		strcpy(args->message.content, argv[4])

		printf("Client %d has issued a PUT request, message = %s\n", args->id, args->message->content);
	}


	free(args);
	clnt_destroy(clnt);

}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	database_1 (host);
exit (0);
}
