/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "database.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rpc_args *
action_1(struct rpc_args *argp, CLIENT *clnt)
{
	static rpc_args clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ACTION,
		(xdrproc_t) xdr_rpc_args, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_args, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
