/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "database.h"


void
database_1(char *host, char *action)
{
    printf("running client\n");
    printf("Action: %s\n", action);
	CLIENT *clnt;
	rpc_args  *result_1;
	struct rpc_args  action_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DATABASE, ASSIGNMENT_7, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = action_1(&action_1_arg, clnt);
	if (result_1 == (rpc_args *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    char *action;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    action = argv[2];
    printf("running client, main\n");
    fflush(stdout);
	database_1 (host, action);
exit (0);
}
