/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATABASE_H_RPCGEN
#define _DATABASE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char content[2000];
};
typedef struct message message;

struct rpc_args {
	char action[20];
	int id;
	struct message message;
};
typedef struct rpc_args rpc_args;

#define DATABASE 0x20fff100
#define ASSIGNMENT_7 1

#if defined(__STDC__) || defined(__cplusplus)
#define ACTION 1
extern  rpc_args * action_1(struct rpc_args *, CLIENT *);
extern  rpc_args * action_1_svc(struct rpc_args *, struct svc_req *);
extern int database_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ACTION 1
extern  rpc_args * action_1();
extern  rpc_args * action_1_svc();
extern int database_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);
extern  bool_t xdr_rpc_args (XDR *, rpc_args*);

#else /* K&R C */
extern bool_t xdr_message ();
extern bool_t xdr_rpc_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATABASE_H_RPCGEN */
